import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css"
config.autoAddCss = false

const outfit = Outfit({
  subsets: ["latin"],
  display: "block",
});

export const metadata: Metadata = {
  title: "Huzaifa Ali",
  description: "Generated by create next app",
  icons: [
    {
      url: "/Vector-4.svg",
      sizes: "250x250",
      type: "image/jpeg",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} selection:text-secondaryColor bg-backgroundColor`}
      >
        {children}
      </body>
    </html>
  );
}
